<?php

namespace App\Filament\Resources\Order\OrderResource\Pages;

use App\Filament\Resources\Order\OrderResource;
use App\Filament\Widgets\StatsOrdersOverview;
use App\Models\Platform\Order;
use Carbon\Carbon;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;

class ListOrder extends ListRecords
{
    protected static string $resource = \App\Filament\Resources\Order\OrderResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\Action::make('Экспорт')->disabled(),
            Actions\Action::make('Догрузить')->action(function () {

                $orders = Order::query()
                    ->where('status', false)
                    ->where('lead_id',null)
                    ->whereDate('updated_at', '>', Carbon::now()->subDays(3)->format('Y-m-d'))
                    ->get();

                foreach ($orders as $order) {

                    \App\Jobs\Platform\SendOrder::dispatch($order);
                }
            }),
        ];
    }

    protected function getHeaderWidgets(): array
    {
        return [
//            StatsOrdersOverview::class
        ]; // TODO: Change the autogenerated stub
    }
}
