<?php

namespace App\Filament\Resources\Order\OrderResource\Pages;

use App\Filament\Resources\Order\OrderResource;
use App\Filament\Widgets\StatsOrdersOverview;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;

class ListOrder extends ListRecords
{
    protected static string $resource = \App\Filament\Resources\Order\OrderResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\Action::make('Экспорт')->disabled(),
            Actions\Action::make('Догрузить'),
        ];
    }

    protected function getHeaderWidgets(): array
    {
        return [
//            StatsOrdersOverview::class
        ]; // TODO: Change the autogenerated stub
    }
}
